# path:
ckpt: # will be overwrite
save_img_path: "./sample_videos/" # will be overwrite
vae: "./configs/vae/autoencoder_kl.yaml"

# model config: 
model: Latte-M/2
num_frames: 16
image_size: 128 # choices=[256, 512]
in_channels: 4
frame_interval: 3
fixed_spatial: False
attention_bias: True
learn_sigma: True
extras: 1 # [1, 2] 1 unconditional generation, 2 class-conditional generation
num_classes:

diffusion_name: 'gaussian_diffusion_v2' # 'gaussian_diffusion' or 'gaussian_diffusion_v2'
# model speedup
use_compile: False
use_fp16: False

# sample config:
seed: 0
sample_method: 'ddim'
num_sampling_steps: 25
cfg_scale: 1.0
negative_name:

local_batch_size: 16
total_samples: 2048

# video config
fps: 8
video_quality: 9

# ddp sample config
per_proc_batch_size: 1
num_fvd_samples: 1